name: URL SHORTNER BuildRelease
on:
  push:
    branches: [ main ]
    paths: 
    - "url-shortner/**"
    - ".github/workflows/build-deploy.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: url-shortner
  IMAGE_TAG: ${{ github.sha }}

jobs:
  lambdaBuildTest:
    name: Project Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
  lambdaImageBuildPush:
    name: Image Build
    needs: [ lambdaBuildTest ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  deployCDK:
    needs: [ lambdaImageBuildPush ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # no time to setup oicd with assume role 
      # https://github.com/aws-actions/configure-aws-credentials
      - name: Configure AWS credentials
        id: assume-role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-session-name: "GithubAction-Session"
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: |
          npm install -g aws-cdk@latest
          pip install -r requirements.txt

      - name: Deploy AWS infrastructure
        run: |
          cdk deploy
